Repository ThaiQ/IBMScholars, pull requests merged in 2020-07, with the labels that each got.

#1 IBM Cloud Deployment and Server (Backend)
  .cfignore
  .gitignore
  api/constants.js
  api/initAPI.js
  api/server.js
  package.json
  server/.ibm-project
  server/Dockerfile
  server/Dockerfile-tools
  server/LICENSE
  server/README.md
  server/cli-config.yml
  server/manifest.yml
  server/package-lock.json
  server/package.json
  server/server/config/swagger-route.js
  server/server/config/swagger.json
  server/server/constants.js
  server/server/controllers/health-controller.js
  server/server/controllers/health-route.js
  server/server/init-tables/add-tables.js
  server/server/init-tables/remove-tables.js
  server/server/merchants/routes.js
  server/server/merchants/table.js
  server/server/server.js
  src/const.js
  src/pages/sample_merchant-page/test.js
Labels: BackEnd, Documentation, Refactoring

#4 Mp3 - Text to Speech (from IBM Cloud)
  package.json
  server/package-lock.json
  server/package.json
  server/server/mp3/mp3/a.mp3
  server/server/mp3/mp3/b.mp3
  server/server/mp3/routes.js
  server/server/mp3/txtTOspeech.js
  server/server/server.js
  src/pages/sample_merchant-page/test.js
Labels: BackEnd, Documentation, FrontEnd

#7 Creates Homepage
  package-lock.json
  package.json
  public/index.html
  src/index.css
  src/index.js
  src/pages/homepage/home.css
  src/pages/homepage/home.js
  src/pages/homepage/pictures/annabel.jpeg
  src/pages/homepage/pictures/mock.jpg
  src/pages/homepage/pictures/nanar.jpeg
  src/pages/homepage/pictures/seema.jpeg
  src/pages/homepage/pictures/surabhi.png
  src/pages/homepage/pictures/thai.png
  src/pages/homepage/pictures/titlePage.png
  src/pages/homepage/teamCard.css
  src/pages/homepage/teamCard.js
Labels: FrontEnd

#5 Community Form
  server/server/comment/routes.js
  server/server/comment/table.js
  server/server/constants.js
  server/server/post/routes.js
  server/server/post/table.js
  server/server/server.js
  src/components/post/post.css
  src/components/post/post.js
  src/pages/forms/forms.css
  src/pages/forms/forms.js
  src/routes.js
Labels: BackEnd, FrontEnd

#13 Reward Page UI Fix
  src/pages/RewardPage/rewards.js
Labels: FrontEnd

#16 Refactored the UI on Community Forum and Reward Page
  src/components/navbar/navbar.js
  src/components/post/post.css
  src/components/post/post.js
  src/pages/RewardPage/rewards.css
  src/pages/RewardPage/rewards.js
  src/pages/forms/forms.css
  src/pages/forms/forms.js
  src/pages/forum/forum.css
  src/pages/forum/forum.js
  src/routes.js
Labels: FrontEnd, Refactoring

#24 Creates Mock Login
  src/components/navbar/navbar.js
  src/pages/Login/login.js
Labels: BackEnd, FrontEnd

#23 Refactored the color palette of Autism and ADHD pages
  src/components/navbar/navbar.js
  src/components/post/post.css
  src/const.js
  src/pages/RewardPage/rewards.js
Labels: FrontEnd, Refactoring

#28 Fixed the UI on Homepage
  src/pages/Disabilities/Autism/autism.js
  src/pages/Disabilities/Autism/disabilities.css
  src/pages/Disabilities/Autism/pictures/abc-blocks.png
  src/pages/Disabilities/Autism/pictures/abc-blocks1.png
  src/pages/Disabilities/Autism/pictures/writing-abc.jpg
  src/pages/Login/login.js
  src/pages/homepage/home.css
  src/pages/homepage/home.js
  src/pages/homepage/teamCard.css
  src/pages/homepage/teamCard.js
Labels: FrontEnd, Refactoring
